services:
  overlay-dev-container:
    build:
      context: ..
      dockerfile: ./local-data/overlay-dev-container/Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      MONGO_URL: mongodb://mongo:27017/overlay-db
      KNEX_URL: mysql://overlayAdmin:overlay123@mysql:3306/overlay
      SERVER_PRIVATE_KEY: dbc08836585bea6ed77410caa55fb47d66e0b8839c97cd90c6d76f49002560a5
      HOSTING_URL: localhost:8080
      NETWORK: mainnet
      REQUEST_LOGGING: "true"
      GASP_SYNC: "false"
      LOG_TIME: "false"
      LOG_PREFIX: "[LARS OVERLAY ENGINE] "
      THROW_ON_BROADCAST_FAIL: "false"
      SYNC_CONFIG_JSON: "{}"
    depends_on:
      - mysql
      - mongo
    volumes:
      - /Users/peterdemichiel/Desktop/metanet-labs/lab-l9/backend/src:/app/src
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: overlay
      MYSQL_USER: overlayAdmin
      MYSQL_PASSWORD: overlay123
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - /Users/peterdemichiel/Desktop/metanet-labs/lab-l9/local-data/mysql:/var/lib/mysql
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
      interval: 10s
      timeout: 5s
      retries: 3
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
  mongo:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - /Users/peterdemichiel/Desktop/metanet-labs/lab-l9/local-data/mongo:/data/db
    command:
      - mongod
      - --quiet
  mongoexpress:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_BASICAUTH_USERNAME: ""
      ME_CONFIG_BASICAUTH_PASSWORD: ""
    depends_on:
      - mongo
